const APP=document.getElementById("app"),API_BASE=(window.PARFUM_AGENTE_API||"").replace(/\/$/,"");
let DATA={},state={stage:"intro",index:0,answers:{},result:null,web:null};
async function load(){try{const [q,f,a,c]=await Promise.all(["questions","fragrances","archetypes","engine-config"].map(x=>fetch(`data/${x}.json`).then(r=>{if(!r.ok)throw Error(`${x}.json failed to load`);return r.json()})));Object.assign(DATA,{questions:q.questions,fragrances:f.fragrances,archetypes:a.archetypes,config:c});render()}catch(e){APP.innerHTML=`<div class="error"><b>Parfum Agente could not load its scent data.</b><br><br>${esc(e.message)}</div>`}}
function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function announce(){APP.focus({preventScroll:true});window.scrollTo({top:0,behavior:"smooth"})}
function reset(){state={stage:"quiz",index:0,answers:{},result:null,web:null};render();announce()}
function home(){state={stage:"intro",index:0,answers:{},result:null,web:null};render();announce()}
function back(){if(state.index>0){state.index--;render();announce()}else home()}
function render(){if(state.stage==="intro")intro();else if(state.stage==="quiz")quiz();else if(state.stage==="loading")loading();else results()}
function intro(){APP.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="kicker">Local-first scent intelligence</span><div class="eyebrow">Meet your personal fragrance agent</div><h1>Your nose already knows.<br><span class="gold">We put it into words.</span></h1><p class="lead">A thoughtful scent quiz that translates what you love into a personal Scent DNA—and introduces fragrances that feel unmistakably you.</p><div class="hero-actions"><button class="btn" onclick="reset()">Discover my Scent DNA</button><span class="small">About 2 minutes · No account required</span></div></div><div class="bottle-orbit" aria-hidden="true"><span class="orbit"></span><span class="bottle"></span></div></div><div class="trust-row"><div class="trust-item"><b>Personal</b>Built around your taste, mood and rituals.</div><div class="trust-item"><b>Private</b>Your quiz stays in your browser by default.</div><div class="trust-item"><b>Practical</b>Clear matches, notes and reasons—not hype.</div></div></section>`}
function quiz(){const q=DATA.questions[state.index];APP.innerHTML=`<section><div class="quiz-head"><div class="eyebrow">Scent consultation · ${state.index+1} of ${DATA.questions.length}</div><button class="ghost" onclick="back()" aria-label="Go to previous question">Back</button></div><div class="progress" aria-label="Quiz progress">${DATA.questions.map((_,i)=>`<i class="${i<state.index?"done":i===state.index?"on":""}"></i>`).join("")}</div><h2>${esc(q.text)}</h2><p class="help">Choose what feels most like you. There are no wrong answers.</p>${q.options.map((o,i)=>`<button class="choice" onclick="pick(${i})">${esc(o.label)}</button>`).join("")}</section>`}
function pick(i){const q=DATA.questions[state.index];state.answers[q.id]=q.options[i].id;if(state.index<DATA.questions.length-1){state.index++;render();announce()}else{state.stage="loading";render();announce()}}
function loading(){APP.innerHTML=`<div style="text-align:center;padding-top:80px"><div class="spinner" aria-hidden="true"></div><h2>Translating your Scent DNA…</h2><p class="lead" style="margin-inline:auto">Matching your preferences against the Parfum Agente fragrance library.</p></div>`;setTimeout(build,450)}
function build(){const profile=ParfumAgenteScentEngine.buildUserProfile(state.answers,DATA.questions,DATA.config);const archetype=ParfumAgenteScentEngine.getArchetype(profile,DATA.archetypes);const local=ParfumAgenteScentEngine.getRecommendations(profile,DATA.fragrances,DATA.config,{minScore:60}).slice(0,5);state.result={profile,archetype,local};state.stage="results";render();announce();if(API_BASE)discoverWeb(profile,local)}
async function discoverWeb(profile,local){try{const res=await fetch(API_BASE+"/recommend",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile,localCandidates:local.map(x=>({id:x.id,brand:x.brand,name:x.name,score:x.match.score,families:x.families,notes:x.notes}))})});if(!res.ok)throw new Error("Web discovery unavailable");state.web=await res.json();render()}catch(e){state.web={enabled:false,error:e.message};render()}}
function dna(profile){return Object.entries(profile.scentDNA).map(([k,v])=>`<div class="small">${esc(k)} · ${Math.round(v)}%</div><div class="bar"><i style="width:${Math.max(0,Math.min(100,v))}%"></i></div>`).join("")}
function recCard(x,web=false){const links=(x.retailers||[]).filter(r=>r.url&&r.name);const score=Math.round(x.match?.score??x.matchScore??x.webMatch??x.score??0);return `<article class="card ${x.isBest?"best":""}"><div style="display:flex;justify-content:space-between;gap:10px"><div class="serif" style="font-size:21px">${esc(x.name)}</div><div class="score" aria-label="${score} percent match">${score}%</div></div><div class="brand">${esc(x.brand)}</div><div class="notes">${esc(x.notes?.base?.join(", ")||x.notes?.middle?.join(", ")||"Fragrance profile available")}</div><div class="why">${esc(x.why||"This fragrance shares key characteristics with your scent profile.")}</div>${web?`<div class="source">Source: Fragella${x.purchaseUrl?` · <a href="${esc(x.purchaseUrl)}" target="_blank" rel="noopener">Purchase information</a>`:""}</div>`:""}${links.map(l=>`<a class="buy" href="${esc(l.url)}" target="_blank" rel="noopener sponsored">${esc(l.name)} →</a>`).join(" ")}</article>`}
function summaryText(){const a=state.result.archetype.primary,top=state.result.local[0];return `My Parfum Agente scent identity is ${a.name}: ${a.tagline}. My top fragrance match is ${top.brand} ${top.name} at ${top.match.score}%. Discover your Scent DNA with Parfum Agente.`}
async function shareResult(){const text=summaryText();try{if(navigator.share)await navigator.share({title:"My Parfum Agente Scent DNA",text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);toast("Result copied—ready to share.")}}catch(e){if(e.name!=="AbortError")toast("Sharing is not available in this browser.")}}
function toast(message){const el=document.createElement("div");el.className="toast";el.role="status";el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2400)}
function results(){const r=state.result,p=r.profile,a=r.archetype,w=state.web,webCards=w?.recommendations||[];APP.innerHTML=`<section><div class="result-header"><div class="eyebrow">Your scent identity</div><h1 class="result-name">${esc(a.primary.name)}</h1><p class="lead centered">${esc(a.primary.tagline)}.</p></div><div class="card"><div class="eyebrow">Your Scent DNA</div>${dna(p)}</div><div class="pyramid"><div style="width:58%">TOP<br><span class="small">${esc((p.preferredNotes||[]).slice(0,3).join(" · ")||"fresh notes")}</span></div><div style="width:78%">HEART<br><span class="small">${esc((p.preferredNotes||[]).slice(3,6).join(" · ")||"aromatic notes")}</span></div><div style="width:100%">BASE<br><span class="small">${esc((p.preferredNotes||[]).slice(6,8).join(" · ")||"woods · musk")}</span></div></div><div class="eyebrow">Your closest matches</div>${r.local.map((x,i)=>recCard({...x,isBest:i===0})).join("")}<div class="eyebrow live-heading">Live product discovery</div>${API_BASE?(w?.enabled===false?`<div class="status">Live discovery is temporarily unavailable. Your local recommendations are still valid.</div>`:webCards.length?webCards.map(x=>recCard(x,true)).join(""):`<div class="status">Searching current product information…</div>`):`<div class="status">The beta currently uses the curated local scent library. Live product discovery will activate when the secure API service is connected.</div>`}<div class="result-actions"><button class="btn" onclick="shareResult()">Share my result</button><button class="ghost" onclick="reset()">Try another profile</button><button class="ghost" onclick="home()">Home</button></div><p class="small result-disclaimer">${esc(DATA.config.disclaimer||"Recommendations are guidance, not objective scientific measurements.")}</p></section>`}
load();
